name: publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Dry run for nx release
        default: true
  release:
    types:
      - published

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.job, github.event.ref) }}
  cancel-in-progress: false

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_PROVENANCE: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          registry-url: "https://registry.npmjs.org"
          scope: "plastic-ant"

      - run: npm whoami && echo "NPM credentials are valid" || (echo "NPM credentials are invalid or have expired." && exit 1)

      - run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build

      - run: npx nx run nx-cdk:build --skip-nx-cache

      - run: npx nx release publish --dry-run=${{ env.DRY_RUN }}
        env:
          DRY_RUN: ${{ github.ref_type != 'tag' || (github.event_name == 'workflow_dispatch' && inputs.dry-run) }}

      - run: |
          git push
          git push --tags
